CREATE TABLE ranz.Lugar
(Id_Lugar INT AUTO_INCREMENT NOT NULL,
Nombre VARCHAR(55) NOT NULL,
Descripcion TEXT NOT NULL,
Telefono VARCHAR(12) NOT NULL,
Email VARCHAR(255) NOT NULL,
Facebook VARCHAR(255) NOT NULL,
Horario DATE NOT NULL,
PRIMARY KEY(Id_Lugar))ENGINE=INNODB;